### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by bvdx199** [dslapelis/IMEI-Track#3]
does somebody knows the password? when using the comment java -r imei_jar

and how do i build this?

**Comment by dslapelis** [comment]
Hi there.

This application simply connects to a remote database. The password is that of the user used to connect to the database. For example, there are database connection strings found in the source code starting here: https://github.com/dslapelis/IMEI-Track/blob/master/src/imei/track/MainFrame.java#L279

I do not have this database set up anymore. You'll have to create a new MySQL database for yourself and modify the connection strings as necessary.

I believe the schema was just a single table called "phones" with columns `owner`, `imei`, and `history`. Unfortunately, as a novice developer when I wrote this, I did not document this well.
